# Generated by Django 5.2.9 on 2026-01-18 14:14

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="الاسم")),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("courses", "الكورسات"),
                            ("articles", "المقالات"),
                            ("grants", "المنح والتدريبات"),
                            ("books", "الكتب والملخصات"),
                        ],
                        max_length=20,
                        verbose_name="نوع الفئة",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="الأيقونة"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
            ],
            options={
                "verbose_name": "القسم",
                "verbose_name_plural": "الأقسام",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="موقع التعليم",
                        max_length=200,
                        verbose_name="اسم الموقع",
                    ),
                ),
                (
                    "site_description",
                    models.TextField(blank=True, null=True, verbose_name="وصف الموقع"),
                ),
                (
                    "site_logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="site/",
                        verbose_name="شعار الموقع",
                    ),
                ),
                (
                    "default_link_delay",
                    models.IntegerField(
                        default=30,
                        help_text="التأخير الافتراضي بالثواني",
                        verbose_name="تأخير الرابط الافتراضي",
                    ),
                ),
                (
                    "allow_comments",
                    models.BooleanField(default=True, verbose_name="السماح بالتعليقات"),
                ),
                (
                    "require_comment_approval",
                    models.BooleanField(
                        default=True, verbose_name="يتطلب موافقة على التعليقات"
                    ),
                ),
                (
                    "maintenance_mode",
                    models.BooleanField(default=False, verbose_name="وضع الصيانة"),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        default="contact@example.com",
                        max_length=254,
                        verbose_name="البريد الإلكتروني للتواصل",
                    ),
                ),
                (
                    "facebook_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="رابط الفيسبوك"
                    ),
                ),
                (
                    "twitter_url",
                    models.URLField(blank=True, null=True, verbose_name="رابط تويتر"),
                ),
                (
                    "instagram_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="رابط إنستغرام"
                    ),
                ),
                (
                    "youtube_url",
                    models.URLField(blank=True, null=True, verbose_name="رابط يوتيوب"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "إعدادات الموقع",
                "verbose_name_plural": "إعدادات الموقع",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="العنوان")),
                (
                    "slug",
                    models.SlugField(
                        max_length=250, unique=True, verbose_name="الرابط"
                    ),
                ),
                ("content", ckeditor.fields.RichTextField(verbose_name="المحتوى")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="posts/featured/%Y/%m/%d/",
                        verbose_name="الصورة القديمة",
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True,
                        upload_to="posts/featured/%Y/%m/",
                        verbose_name="الصورة الرئيسية",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        upload_to="posts/thumbnails/%Y/%m/",
                        verbose_name="الصورة المصغرة",
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(blank=True, max_length=300, verbose_name="الملخص"),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="رابط خارجي"),
                ),
                (
                    "link_delay",
                    models.IntegerField(
                        blank=True, default=30, null=True, verbose_name="تأخير الرابط"
                    ),
                ),
                (
                    "views",
                    models.PositiveIntegerField(default=0, verbose_name="المشاهدات"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("published", "منشور"),
                            ("private", "خاص"),
                            ("archived", "مؤرشف"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "publish_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ النشر"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="عنوان SEO"
                    ),
                ),
                (
                    "seo_description",
                    models.TextField(
                        blank=True, max_length=300, verbose_name="وصف SEO"
                    ),
                ),
                (
                    "seo_keywords",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="كلمات مفتاحية SEO"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المؤلف",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="core.category",
                        verbose_name="الفئة",
                    ),
                ),
            ],
            options={
                "verbose_name": "منشور",
                "verbose_name_plural": "المنشورات",
                "ordering": ["-publish_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="الاسم")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="البريد الإلكتروني"),
                ),
                ("content", models.TextField(verbose_name="المحتوى")),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="معتمد"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="core.post",
                        verbose_name="المنشور",
                    ),
                ),
            ],
            options={
                "verbose_name": "تعليق",
                "verbose_name_plural": "التعليقات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PostBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("text", "نص"),
                            ("image", "صورة"),
                            ("video", "فيديو"),
                            ("code", "كود"),
                            ("quote", "اقتباس"),
                        ],
                        max_length=10,
                        verbose_name="نوع البلوك",
                    ),
                ),
                (
                    "text",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="النص"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blog/blocks/%Y/%m/",
                        verbose_name="الصورة",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="core.post",
                        verbose_name="المنشور",
                    ),
                ),
            ],
            options={
                "verbose_name": "بلوك المحتوى",
                "verbose_name_plural": "بلوكات المحتوى",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SystemLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("info", "معلومات"),
                            ("warning", "تحذير"),
                            ("error", "خطأ"),
                            ("security", "أمني"),
                        ],
                        default="info",
                        max_length=20,
                        verbose_name="نوع السجل",
                    ),
                ),
                ("message", models.TextField(verbose_name="الرسالة")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="عنوان IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, null=True, verbose_name="معلومات المتصفح"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل النظام",
                "verbose_name_plural": "سجلات النظام",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="الاسم الكامل"
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, null=True, verbose_name="السيرة الذاتية"
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profile_images/",
                        verbose_name="صورة الملف الشخصي",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="الهاتف"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الميلاد"
                    ),
                ),
                (
                    "is_content_editor",
                    models.BooleanField(default=False, verbose_name="محرر محتوى"),
                ),
                (
                    "can_manage_comments",
                    models.BooleanField(
                        default=False, verbose_name="يمكنه إدارة التعليقات"
                    ),
                ),
                (
                    "can_manage_categories",
                    models.BooleanField(
                        default=False, verbose_name="يمكنه إدارة الأقسام"
                    ),
                ),
                (
                    "posts_count",
                    models.IntegerField(default=0, verbose_name="عدد المنشورات"),
                ),
                (
                    "comments_count",
                    models.IntegerField(default=0, verbose_name="عدد التعليقات"),
                ),
                (
                    "last_active",
                    models.DateTimeField(auto_now=True, verbose_name="آخر نشاط"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملف المستخدم",
                "verbose_name_plural": "ملفات المستخدمين",
            },
        ),
    ]
