# Generated by Django 5.2.9 on 2026-01-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="heroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="العنوان")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="العنوان الفرعي"
                    ),
                ),
                (
                    "background_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="site/hero/",
                        verbose_name="صورة الخلفية",
                    ),
                ),
            ],
            options={
                "verbose_name": "hero قسم",
                "verbose_name_plural": "hero قسم",
            },
        ),
        migrations.DeleteModel(
            name="PostBlock",
        ),
    ]
