# Generated by Django 5.2.9 on 2026-01-18 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_herosection_delete_postblock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="twitter_url",
        ),
    ]
