# Generated by Django 5.2.9 on 2026-01-18 19:52

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم التنبيه")),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("high_traffic", "حركة مرور عالية"),
                            ("low_traffic", "حركة مرور منخفضة"),
                            ("new_country", "دولة جديدة"),
                            ("high_bounce", "ارتداد مرتفع"),
                            ("long_session", "جلسة طويلة"),
                        ],
                        max_length=50,
                        verbose_name="نوع التنبيه",
                    ),
                ),
                ("threshold", models.IntegerField(verbose_name="الحد الأدنى")),
                ("enabled", models.BooleanField(default=True, verbose_name="مفعل")),
                (
                    "recipients",
                    models.JSONField(default=list, verbose_name="المستلمون"),
                ),
                (
                    "last_triggered",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر تشغيل"
                    ),
                ),
            ],
            options={
                "verbose_name": "قاعدة تنبيه",
                "verbose_name_plural": "قواعد التنبيهات",
            },
        ),
        migrations.CreateModel(
            name="AnalyticsDashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم اللوحة")),
                (
                    "widgets",
                    models.JSONField(default=list, verbose_name="عناصر الواجهة"),
                ),
                (
                    "refresh_interval",
                    models.PositiveIntegerField(
                        default=30, verbose_name="فترة التحديث (ثانية)"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="افتراضي"),
                ),
            ],
            options={
                "verbose_name": "لوحة تحليلات",
                "verbose_name_plural": "لوحات التحليلات",
            },
        ),
        migrations.CreateModel(
            name="AnalyticsSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enable_tracking",
                    models.BooleanField(default=True, verbose_name="تفعيل التتبع"),
                ),
                (
                    "anonymize_ip",
                    models.BooleanField(default=True, verbose_name="إخفاء عناوين IP"),
                ),
                (
                    "store_user_data",
                    models.BooleanField(
                        default=True, verbose_name="تخزين بيانات المستخدم"
                    ),
                ),
                (
                    "dashboard_refresh_interval",
                    models.PositiveIntegerField(
                        default=30, verbose_name="فترة تحديث الداشبورد (ثانية)"
                    ),
                ),
            ],
            options={
                "verbose_name": "إعدادات التحليلات",
                "verbose_name_plural": "إعدادات التحليلات",
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم الدولة")),
                (
                    "code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="كود الدولة"
                    ),
                ),
                (
                    "flag_emoji",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="إيموجي العلم",
                    ),
                ),
                (
                    "visits",
                    models.PositiveIntegerField(default=0, verbose_name="عدد الزيارات"),
                ),
                (
                    "total_time_spent",
                    models.DurationField(
                        default=datetime.timedelta(0),
                        verbose_name="إجمالي الوقت المنقضي",
                    ),
                ),
                (
                    "last_visit",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر زيارة"
                    ),
                ),
            ],
            options={
                "verbose_name": "دولة",
                "verbose_name_plural": "الدول",
                "ordering": ["-visits"],
            },
        ),
        migrations.CreateModel(
            name="RealTimeStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="اسم الإحصائية"
                    ),
                ),
                ("value", models.JSONField(default=dict, verbose_name="القيمة")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
                ),
            ],
            options={
                "verbose_name": "إحصائية فورية",
                "verbose_name_plural": "إحصائيات فورية",
            },
        ),
        migrations.CreateModel(
            name="SiteAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="التاريخ")),
                (
                    "page_views",
                    models.PositiveIntegerField(
                        default=0, verbose_name="مشاهدات الصفحات"
                    ),
                ),
                (
                    "unique_visitors",
                    models.PositiveIntegerField(default=0, verbose_name="زوار فريدون"),
                ),
                (
                    "sessions",
                    models.PositiveIntegerField(default=0, verbose_name="جلسات"),
                ),
                (
                    "bounce_rate",
                    models.FloatField(default=0.0, verbose_name="معدل الارتداد"),
                ),
                (
                    "avg_session_duration",
                    models.DurationField(
                        default=datetime.timedelta(0), verbose_name="متوسط مدة الجلسة"
                    ),
                ),
                (
                    "courses_views",
                    models.PositiveIntegerField(
                        default=0, verbose_name="مشاهدات الكورسات"
                    ),
                ),
                (
                    "articles_views",
                    models.PositiveIntegerField(
                        default=0, verbose_name="مشاهدات المقالات"
                    ),
                ),
                (
                    "grants_views",
                    models.PositiveIntegerField(
                        default=0, verbose_name="مشاهدات المنح"
                    ),
                ),
                (
                    "books_views",
                    models.PositiveIntegerField(
                        default=0, verbose_name="مشاهدات الكتب"
                    ),
                ),
                (
                    "new_users",
                    models.PositiveIntegerField(default=0, verbose_name="مستخدمين جدد"),
                ),
                (
                    "active_users",
                    models.PositiveIntegerField(
                        default=0, verbose_name="مستخدمين نشطين"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "إحصائيات الموقع",
                "verbose_name_plural": "إحصائيات الموقع",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(max_length=100, verbose_name="نوع النشاط"),
                ),
                ("description", models.TextField(verbose_name="الوصف")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="بيانات إضافية"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="الوقت"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "نشاط المستخدم",
                "verbose_name_plural": "أنشطة المستخدمين",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="VisitorSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="معرف الجلسة",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="عنوان IP")),
                ("user_agent", models.TextField(verbose_name="معلومات المتصفح")),
                (
                    "device_type",
                    models.CharField(max_length=50, verbose_name="نوع الجهاز"),
                ),
                ("browser", models.CharField(max_length=100, verbose_name="المتصفح")),
                (
                    "browser_version",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="إصدار المتصفح",
                    ),
                ),
                ("os", models.CharField(max_length=100, verbose_name="نظام التشغيل")),
                (
                    "os_version",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="إصدار نظام التشغيل",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="المنطقة"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="المدينة"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="خط العرض",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="خط الطول",
                    ),
                ),
                (
                    "referrer",
                    models.URLField(blank=True, null=True, verbose_name="المصدر"),
                ),
                ("landing_page", models.URLField(verbose_name="صفحة الهبوط")),
                (
                    "start_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت البدء"),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت الانتهاء"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشطة")),
                (
                    "page_count",
                    models.PositiveIntegerField(default=1, verbose_name="عدد الصفحات"),
                ),
                (
                    "total_time_spent",
                    models.DurationField(
                        default=datetime.timedelta(0),
                        verbose_name="إجمالي الوقت المنقضي",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="بيانات إضافية"
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="analytics.country",
                        verbose_name="الدولة",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "جلسة زائر",
                "verbose_name_plural": "جلسات الزوار",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="RealTimeVisitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_page", models.URLField(verbose_name="الصفحة الحالية")),
                (
                    "time_on_page",
                    models.DurationField(
                        default=datetime.timedelta(0), verbose_name="الوقت في الصفحة"
                    ),
                ),
                (
                    "last_activity",
                    models.DateTimeField(auto_now=True, verbose_name="آخر نشاط"),
                ),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="realtime",
                        to="analytics.visitorsession",
                        verbose_name="الجلسة",
                    ),
                ),
            ],
            options={
                "verbose_name": "زائر فوري",
                "verbose_name_plural": "الزوار الفوريين",
                "ordering": ["-last_activity"],
            },
        ),
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(verbose_name="رابط الصفحة")),
                (
                    "title",
                    models.CharField(max_length=500, verbose_name="عنوان الصفحة"),
                ),
                ("time_spent", models.DurationField(verbose_name="الوقت المنقضي")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="الوقت"),
                ),
                (
                    "scroll_depth",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عمق التمرير (%)"
                    ),
                ),
                (
                    "is_bounce",
                    models.BooleanField(default=False, verbose_name="ارتداد"),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pageviews",
                        to="analytics.visitorsession",
                        verbose_name="الجلسة",
                    ),
                ),
            ],
            options={
                "verbose_name": "مشاهدة صفحة",
                "verbose_name_plural": "مشاهدات الصفحات",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="visitorsession",
            index=models.Index(
                fields=["session_id"], name="analytics_v_session_2e76e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visitorsession",
            index=models.Index(
                fields=["start_time"], name="analytics_v_start_t_aac797_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visitorsession",
            index=models.Index(
                fields=["country"], name="analytics_v_country_7673bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visitorsession",
            index=models.Index(
                fields=["is_active"], name="analytics_v_is_acti_a38255_idx"
            ),
        ),
    ]
